x-shared-env: &shared-fe-env
  NODE_ENV: ${NODE_ENV:-}
  NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL:-}
  NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-}

services:
  hint-frontend:
    image: hint-frontend:latest
    ports:
      - '3000:3000'
    environment:
      <<: *shared-fe-env
