name: Deploy Frontend to EC2

on:
  push:
    branches:
      - version2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVATE_KEY_EC2 }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.HOST_EC2 }} >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME_EC2 }}@${{ secrets.HOST_EC2 }} "echo ✅ SSH connected"
      
      - name: Debug SSH
        run: ssh -vvv -i ~/.ssh/id_ed25519 ${{ secrets.USERNAME_EC2 }}@${{ secrets.HOST_EC2 }} "echo ✅ Connected"

      - name: Deploy Frontend
        run: |
          ssh ${{ secrets.USERNAME_EC2 }}@${{ secrets.HOST_EC2 }} << 'EOF'
            cd /home/ec2-user/ai-agent-fe
            git pull origin version2
            pnpm install
            pnpm build
            pm2 restart ai-agent-fe || pm2 start pnpm --name ai-agent-fe -- start
          EOF
