name: Deploy Frontend to EC2

on:
  push:
    branches:
      - version2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn từ GitHub
        uses: actions/checkout@v3

      - name: Cài SSH Key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_EC2 }}

      - name: Deploy lên EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME_EC2 }}@${{ secrets.HOST_EC2 }} << 'EOF'
            cd ~/ai-chatbot-dashboard
            git pull origin version2
            pnpm install
            pnpm build
            pm2 restart ai-agent-fe || pm2 start pnpm --name ai-agent-fe -- start
          EOF
